[project]
name = "toastman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyperclip>=1.9.0",
    "requests>=2.32.4",
    "textual>=5.0.0",
    "textual-dev>=1.7.0",
]
